FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y dnsutils tcpdump && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 5000

CMD ["python3", "app.py"]

